stages:
  - test

test_java_client:
  image: openjdk:8
  stage: test
  script:
  - java -classpath "java/lib/*:java/jar/eby-client.jar" uk.ac.ebi.webservices.jaxrs.EBeyeClient --getNumberOfResults hgnc human --endpoint http://www.ebi.ac.uk/ebisearch/ws/rest -debugLevel 1 | grep -q '14' ;  [ $? -eq 0 ]  || exit 1


test_perl_client:
  image: perl:latest
  stage: test
  before_script:
  - perl -MCPAN -e 'install XML::Simple'
  - perl -MCPAN -e 'install LWP::Protocol::https'
  script:
  - ./perl/ebeye_lwp.pl getFacetedResults hgnc human "id" | grep -q 'HGNC:20981' ;  [ $? -eq 0 ]  || exit 1


test_python_client:
  image: python:latest
  stage: test
  before_script:
  - pip install requests
  script:
  - python python/ebeye_requests.py getNumberOfResults uniprot VAV_HUMAN | grep -q '1';[ $? -eq 0 ]  || exit 1
  - python python/ebeye_requests.py getEntries uniprot "Q9GZU1,P80567"  "acc,organism_scientific_name" | echo $(grep -c 'Q9GZU1\|D6W647\|Homo sapiens\|Bacillus cereus') | grep -q '4';[ $? -eq 0 ]  || exit 1