image: openjdk:8

stages:
  - build

build:
  stage: build
  script:
  - java -classpath "java/lib/*:java/jar/eby-client.jar" uk.ac.ebi.webservices.jaxrs.EBeyeClient --getNumberOfResults hgnc human --endpoint http://www.ebi.ac.uk/ebisearch/ws/rest -debugLevel 1 | grep -q '14' ; exit 1
#  - chmod +x ./java/javaTestCases.sh
#  - ./java/javaTestCases.sh
#  - java  -classpath java/lib/*:java/EBeye_JAXRS.jar uk.ac.ebi.webservices.jaxrs.EBeyeClient --getNumberOfResults hgnc human --endpoint http://www.ebi.ac.uk/ebisearch/ws/rest -debugLevel 1 | grep -q '15' ; echo $?
#  - java -classpath "java/lib/*" -Djava.ext.dirs=java/lib/ -jar java/EBeye_JAXRS.jar --getNumberOfResults hgnc human --endpoint http://www.ebi.ac.uk/ebisearch/ws/rest -debugLevel 1 | grep -q '15' ; echo $?
#  - java -Djava.ext.dirs=java/lib/* -jar java/EBeye_JAXRS.jar
#  - java  -classpath java/lib/*:java/EBeye_JAXRS.jar uk.ac.ebi.webservices.jaxrs.EBeyeClient