image: java:8

stages:
  - build

build:
  stage: build
  script:
#  - java  -classpath "java/lib/*:java/EBeye_JAXRS.jar" uk.ac.ebi.webservices.jaxrs.EBeyeClient --getNumberOfResults hgnc human --endpoint http://www.ebi.ac.uk/ebisearch/ws/rest -debugLevel 1 | grep -q '15' ; exit $?
  - cd java
  - java -Djava.ext.dirs=lib/ -jar jar/EBeye_JAXRS.jar --getNumberOfResults hgnc human --endpoint http://www.ebi.ac.uk/ebisearch/ws/rest -debugLevel 1 | grep -q '15' ; exit $?

